const mongoose=require('mongoose');
const homeSchema=mongoose.Schema({
    id:{
        type:String,
        required:false,
    },
    location:{
        type:String,
        required:false,
    },
    parking:{
        type:String,
        required:false,
    },
    balconies:{
        type:String,
        required:false,
    },
    numberOfRooms:{
        type:String,
        required:false,
    },
    surfaceArea:{
        type:String,
        required:false,
    },
    furniture:{
        type:String,
        required:false,
    },
    NewlyBuild:{
        type:String,
        required:false,
    },

    photos:{
        type:String,
        required:false,
    },
    available:{
        type:String,
        required:false,
    },
    timesRentedBefore:{
        type:String,
        required:false,
    },
    cost:{
        type:String,
        required:true,
    },
    status:{
        type:String,
        required:false,
    },

})
module.exports=mongoose.model('Home',homeSchema)